### ISSUE TITLE
Connection state: Error...

### ISSUE THREAD

**Issue by jminardi** [OctoPrint/OctoPrint-Netconnectd#4]
I am testing out a new WiFi dongle (TP-LINK TL-WDN4200 N900) and it seems to work with the Raspi 2.

On boot I am able to connect to my WiFi network. I navigated to OctoPrint and in the Network Connection settings I see:

`Connection state: Error while talking to netconnectd, is the service running?, no wifi interface present`

I sshed into the machine an ran netconnectcli status. The result:

```
pi@octopi ~ $ netconnectcli status
SuccessResponse:
  connections:
    ap:
      False
    wifi:
      True
    wired:
      False
  devs:
    [
      wlan0
    ]
  wifi:
    valid_config:
      True
    current_address:
      8A:15:14:EF:21:02
    present:
      True
    current_ssid:
      Greentown Labs Legacy
  link:
    True
```

list_wifi however hangs for a few seconds and then errors out:

```
pi@octopi ~ $ netconnectcli list_wifi
ErrorResponse:
  error while processing message from client
```

I booted into the desktop and was able to see the available wifi networks around me, so scanning does work with this wifi dongle.

Any advice on next steps for debugging?

**Comment by PaulsPi** [comment]
Got the same issue, did you already solve it?

**Comment by foosel** [comment]
Project is no longer actively maintained, sorry.
